modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="elainamod"
version="1.0.0"
displayName="ElainaMod"
credits="伊蕾娜教代行教皇(Elaina Model)---https://space.bilibili.com/519088494"
displayURL="https://shicyaelaina.github.io/index.html"
updateJSONURL="https://curseforge.com/minecraft/mc-mods/elainamod"
issueTrackerURL="https://github.com/ShicyAElaina/elainamod/issue"
authors="Shicy"
description='''
This Mod adds some items from the light novel The Journey of Elaina
'''

[[dependencies.elainamod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"



[[dependencies.elainamod]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elainamod]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

